const KIT_SHARED_INCLUDES = [
  "2 dental trays",
  "2 blue dental putty",
  "2 white dental putty",
  "1 silicone dispenser",
];

module.exports = {
  SHIPPING_ZONES: {
  uk: {
    label: "United Kingdom",
    kitFee: 20,
    kitShipping: 0,
    finishShipping: 6.99,
    kitLabel: "Mould kit (UK, all-in)",
  },
  ireland: {
    label: "Ireland",
    kitFee: 10,
    kitShipping: 9.99,
    finishShipping: 9.99,
    kitLabel: "Mould kit materials",
  },
  "europe-eu": {
    label: "Europe (EU)",
    kitFee: 10,
    kitShipping: 12.99,
    finishShipping: 10.99,
    kitLabel: "Mould kit materials",
  },
  "europe-non-eu": {
    label: "Europe (non-EU)",
    kitFee: 10,
    kitShipping: 14.99,
    finishShipping: 13.99,
    kitLabel: "Mould kit materials",
  },
  "us-canada": {
    label: "United States & Canada",
    kitFee: 10,
    kitShipping: 15.99,
    finishShipping: 13.99,
    kitLabel: "Mould kit materials",
  },
  "australia-nz": {
    label: "Australia & New Zealand",
    kitFee: 10,
    kitShipping: 17.99,
    finishShipping: 16.99,
    kitLabel: "Mould kit materials",
  },
  "middle-east": {
    label: "Middle East",
    kitFee: 10,
    kitShipping: 18.99,
    finishShipping: 15.99,
    kitLabel: "Mould kit materials",
  },
  asia: {
    label: "Asia",
    kitFee: 10,
    kitShipping: 16.99,
    finishShipping: 13.99,
    kitLabel: "Mould kit materials",
  },
  africa: {
    label: "Africa",
    kitFee: 10,
    kitShipping: 18.99,
    finishShipping: 15.99,
    kitLabel: "Mould kit materials",
  },
  "south-america": {
    label: "South & Central America",
    kitFee: 10,
    kitShipping: 18.99,
    finishShipping: 15.99,
    kitLabel: "Mould kit materials",
  },
  "rest-of-world": {
    label: "Rest of World",
    kitFee: 10,
    kitShipping: 19.99,
    finishShipping: 15.99,
    kitLabel: "Mould kit materials",
  },
},
  MATERIAL_OPTIONS: [
  { id: "dental-gold", label: "Dental Gold" },
  { id: "sterling-silver", label: "Sterling Silver" },
  { id: "argentium-silver", label: "Argentium Silver" },
  { id: "9ct-yellow-gold", label: "9ct Yellow Gold" },
  { id: "9ct-white-gold", label: "9ct White Gold" },
  { id: "14ct-yellow-gold", label: "14ct Yellow Gold" },
  { id: "14ct-white-gold", label: "14ct White Gold" },
],
  MATERIAL_ID_ALIASES: {
  "18ct-yellow-gold": "14ct-yellow-gold",
  "18ct-white-gold": "14ct-white-gold",
},
  STONE_OPTIONS: [
  { id: "cubic-zirconia", label: "Cubic Zirconia" },
  { id: "moissanite", label: "Moissanite" },
  { id: "vvs-lab-diamonds", label: "VVS Lab Diamonds" },
  { id: "vs-natural-diamonds", label: "VS Natural Diamonds" },
],
  HAND_SET_DIAMOND_PRICES: {
  "diamond-canine": {
    "sterling-silver": {
      "cubic-zirconia": 330,
      "moissanite": 370,
      "vvs-lab-diamonds": 770,
      "vs-natural-diamonds": 1020
    },
    "argentium-silver": {
      "cubic-zirconia": 330,
      "moissanite": 370,
      "vvs-lab-diamonds": 770,
      "vs-natural-diamonds": 1020
    },
    "dental-gold": {
      "cubic-zirconia": 570,
      "moissanite": 620,
      "vvs-lab-diamonds": 995,
      "vs-natural-diamonds": 1250
    },
    "9ct-yellow-gold": {
      "cubic-zirconia": 570,
      "moissanite": 620,
      "vvs-lab-diamonds": 995,
      "vs-natural-diamonds": 1250
    },
    "9ct-white-gold": {
      "cubic-zirconia": 570,
      "moissanite": 620,
      "vvs-lab-diamonds": 995,
      "vs-natural-diamonds": 1250
    },
    "14ct-yellow-gold": {
      "cubic-zirconia": 945,
      "moissanite": 995,
      "vvs-lab-diamonds": 1370,
      "vs-natural-diamonds": 1630
    },
    "14ct-white-gold": {
      "cubic-zirconia": 945,
      "moissanite": 1020,
      "vvs-lab-diamonds": 1370,
      "vs-natural-diamonds": 1630
    }
  },
  "diamond-lateral": {
    "sterling-silver": {
      "cubic-zirconia": 260,
      "moissanite": 295,
      "vvs-lab-diamonds": 570,
      "vs-natural-diamonds": 770
    },
    "argentium-silver": {
      "cubic-zirconia": 260,
      "moissanite": 295,
      "vvs-lab-diamonds": 570,
      "vs-natural-diamonds": 770
    },
    "dental-gold": {
      "cubic-zirconia": 450,
      "moissanite": 520,
      "vvs-lab-diamonds": 770,
      "vs-natural-diamonds": 950
    },
    "9ct-yellow-gold": {
      "cubic-zirconia": 450,
      "moissanite": 520,
      "vvs-lab-diamonds": 770,
      "vs-natural-diamonds": 950
    },
    "9ct-white-gold": {
      "cubic-zirconia": 450,
      "moissanite": 520,
      "vvs-lab-diamonds": 770,
      "vs-natural-diamonds": 950
    },
    "14ct-yellow-gold": {
      "cubic-zirconia": 770,
      "moissanite": 870,
      "vvs-lab-diamonds": 1070,
      "vs-natural-diamonds": 1270
    },
    "14ct-white-gold": {
      "cubic-zirconia": 770,
      "moissanite": 870,
      "vvs-lab-diamonds": 1070,
      "vs-natural-diamonds": 1270
    }
  },
  "diamond-heart-canine": {
    "sterling-silver": {
      "cubic-zirconia": 290,
      "moissanite": 330,
      "vvs-lab-diamonds": 620,
      "vs-natural-diamonds": 750
    },
    "argentium-silver": {
      "cubic-zirconia": 290,
      "moissanite": 330,
      "vvs-lab-diamonds": 620,
      "vs-natural-diamonds": 750
    },
    "dental-gold": {
      "cubic-zirconia": 480,
      "moissanite": 520,
      "vvs-lab-diamonds": 720,
      "vs-natural-diamonds": 970
    },
    "9ct-yellow-gold": {
      "cubic-zirconia": 480,
      "moissanite": 520,
      "vvs-lab-diamonds": 720,
      "vs-natural-diamonds": 970
    },
    "9ct-white-gold": {
      "cubic-zirconia": 480,
      "moissanite": 520,
      "vvs-lab-diamonds": 720,
      "vs-natural-diamonds": 970
    },
    "14ct-yellow-gold": {
      "cubic-zirconia": 870,
      "moissanite": 945,
      "vvs-lab-diamonds": 1220,
      "vs-natural-diamonds": 1370
    },
    "14ct-white-gold": {
      "cubic-zirconia": 870,
      "moissanite": 945,
      "vvs-lab-diamonds": 1220,
      "vs-natural-diamonds": 1370
    }
  },
  "diamond-window-canine": {
    "sterling-silver": {
      "cubic-zirconia": 230,
      "moissanite": 270,
      "vvs-lab-diamonds": 410,
      "vs-natural-diamonds": 540
    },
    "argentium-silver": {
      "cubic-zirconia": 230,
      "moissanite": 270,
      "vvs-lab-diamonds": 410,
      "vs-natural-diamonds": 540
    },
    "dental-gold": {
      "cubic-zirconia": 380,
      "moissanite": 445,
      "vvs-lab-diamonds": 595,
      "vs-natural-diamonds": 720
    },
    "9ct-yellow-gold": {
      "cubic-zirconia": 380,
      "moissanite": 445,
      "vvs-lab-diamonds": 595,
      "vs-natural-diamonds": 720
    },
    "9ct-white-gold": {
      "cubic-zirconia": 380,
      "moissanite": 445,
      "vvs-lab-diamonds": 595,
      "vs-natural-diamonds": 720
    },
    "14ct-yellow-gold": {
      "cubic-zirconia": 680,
      "moissanite": 720,
      "vvs-lab-diamonds": 895,
      "vs-natural-diamonds": 1020
    },
    "14ct-white-gold": {
      "cubic-zirconia": 680,
      "moissanite": 720,
      "vvs-lab-diamonds": 895,
      "vs-natural-diamonds": 1020
    }
  },
  "diamond-canine-canine": {
    "sterling-silver": {
      "cubic-zirconia": 600,
      "moissanite": 695,
      "vvs-lab-diamonds": 1495,
      "vs-natural-diamonds": 1995
    },
    "argentium-silver": {
      "cubic-zirconia": 600,
      "moissanite": 695,
      "vvs-lab-diamonds": 1495,
      "vs-natural-diamonds": 1995
    },
    "dental-gold": {
      "cubic-zirconia": 1070,
      "moissanite": 1170,
      "vvs-lab-diamonds": 1970,
      "vs-natural-diamonds": 2470
    },
    "9ct-yellow-gold": {
      "cubic-zirconia": 1070,
      "moissanite": 1170,
      "vvs-lab-diamonds": 1970,
      "vs-natural-diamonds": 2470
    },
    "9ct-white-gold": {
      "cubic-zirconia": 1070,
      "moissanite": 1170,
      "vvs-lab-diamonds": 1970,
      "vs-natural-diamonds": 2470
    },
    "14ct-yellow-gold": {
      "cubic-zirconia": 1820,
      "moissanite": 1920,
      "vvs-lab-diamonds": 2720,
      "vs-natural-diamonds": 3220
    },
    "14ct-white-gold": {
      "cubic-zirconia": 1820,
      "moissanite": 1920,
      "vvs-lab-diamonds": 2720,
      "vs-natural-diamonds": 3220
    }
  },
  "diamond-lateral-lateral": {
    "sterling-silver": {
      "cubic-zirconia": 460,
      "moissanite": 520,
      "vvs-lab-diamonds": 1095,
      "vs-natural-diamonds": 1830
    },
    "argentium-silver": {
      "cubic-zirconia": 460,
      "moissanite": 520,
      "vvs-lab-diamonds": 1095,
      "vs-natural-diamonds": 1830
    },
    "dental-gold": {
      "cubic-zirconia": 840,
      "moissanite": 920,
      "vvs-lab-diamonds": 1470,
      "vs-natural-diamonds": 2220
    },
    "9ct-yellow-gold": {
      "cubic-zirconia": 840,
      "moissanite": 920,
      "vvs-lab-diamonds": 1470,
      "vs-natural-diamonds": 2220
    },
    "9ct-white-gold": {
      "cubic-zirconia": 840,
      "moissanite": 920,
      "vvs-lab-diamonds": 1470,
      "vs-natural-diamonds": 2220
    },
    "14ct-yellow-gold": {
      "cubic-zirconia": 1470,
      "moissanite": 1570,
      "vvs-lab-diamonds": 2100,
      "vs-natural-diamonds": 2845
    },
    "14ct-white-gold": {
      "cubic-zirconia": 1470,
      "moissanite": 1570,
      "vvs-lab-diamonds": 2100,
      "vs-natural-diamonds": 2845
    }
  },
  "diamond-lateral-canine": {
    "sterling-silver": {
      "cubic-zirconia": 530,
      "moissanite": 610,
      "vvs-lab-diamonds": 1295,
      "vs-natural-diamonds": 1720
    },
    "argentium-silver": {
      "cubic-zirconia": 530,
      "moissanite": 610,
      "vvs-lab-diamonds": 1295,
      "vs-natural-diamonds": 1720
    },
    "dental-gold": {
      "cubic-zirconia": 950,
      "moissanite": 1030,
      "vvs-lab-diamonds": 1720,
      "vs-natural-diamonds": 2145
    },
    "9ct-yellow-gold": {
      "cubic-zirconia": 950,
      "moissanite": 1030,
      "vvs-lab-diamonds": 1720,
      "vs-natural-diamonds": 2145
    },
    "9ct-white-gold": {
      "cubic-zirconia": 950,
      "moissanite": 1030,
      "vvs-lab-diamonds": 1720,
      "vs-natural-diamonds": 2145
    },
    "14ct-yellow-gold": {
      "cubic-zirconia": 1645,
      "moissanite": 1745,
      "vvs-lab-diamonds": 2395,
      "vs-natural-diamonds": 2830
    },
    "14ct-white-gold": {
      "cubic-zirconia": 1645,
      "moissanite": 1745,
      "vvs-lab-diamonds": 2395,
      "vs-natural-diamonds": 2830
    }
  },
  "diamond-window-canine-inlay": {
    "sterling-silver": {
      "cubic-zirconia": 245,
      "moissanite": 290,
      "vvs-lab-diamonds": 490,
      "vs-natural-diamonds": 645
    },
    "argentium-silver": {
      "cubic-zirconia": 245,
      "moissanite": 290,
      "vvs-lab-diamonds": 490,
      "vs-natural-diamonds": 645
    },
    "dental-gold": {
      "cubic-zirconia": 530,
      "moissanite": 590,
      "vvs-lab-diamonds": 790,
      "vs-natural-diamonds": 945
    },
    "9ct-yellow-gold": {
      "cubic-zirconia": 530,
      "moissanite": 590,
      "vvs-lab-diamonds": 790,
      "vs-natural-diamonds": 945
    },
    "9ct-white-gold": {
      "cubic-zirconia": 530,
      "moissanite": 590,
      "vvs-lab-diamonds": 790,
      "vs-natural-diamonds": 945
    },
    "14ct-yellow-gold": {
      "cubic-zirconia": 1010,
      "moissanite": 1120,
      "vvs-lab-diamonds": 1270,
      "vs-natural-diamonds": 1470
    },
    "14ct-white-gold": {
      "cubic-zirconia": 1010,
      "moissanite": 1120,
      "vvs-lab-diamonds": 1270,
      "vs-natural-diamonds": 1470
    }
  },
  "diamond-window-lateral-canine": {
    "sterling-silver": {
      "cubic-zirconia": 320,
      "moissanite": 370,
      "vvs-lab-diamonds": 670,
      "vs-natural-diamonds": 890
    },
    "argentium-silver": {
      "cubic-zirconia": 320,
      "moissanite": 370,
      "vvs-lab-diamonds": 670,
      "vs-natural-diamonds": 890
    },
    "dental-gold": {
      "cubic-zirconia": 645,
      "moissanite": 695,
      "vvs-lab-diamonds": 1010,
      "vs-natural-diamonds": 1230
    },
    "9ct-yellow-gold": {
      "cubic-zirconia": 645,
      "moissanite": 695,
      "vvs-lab-diamonds": 1010,
      "vs-natural-diamonds": 1230
    },
    "9ct-white-gold": {
      "cubic-zirconia": 645,
      "moissanite": 695,
      "vvs-lab-diamonds": 1010,
      "vs-natural-diamonds": 1230
    },
    "14ct-yellow-gold": {
      "cubic-zirconia": 1195,
      "moissanite": 1270,
      "vvs-lab-diamonds": 1570,
      "vs-natural-diamonds": 1770
    },
    "14ct-white-gold": {
      "cubic-zirconia": 1195,
      "moissanite": 1270,
      "vvs-lab-diamonds": 1570,
      "vs-natural-diamonds": 1770
    }
  },
  "window-canine-diamond-inlay": {
    "sterling-silver": {
      "cubic-zirconia": 190,
      "moissanite": 220,
      "vvs-lab-diamonds": 270,
      "vs-natural-diamonds": 320
    },
    "argentium-silver": {
      "cubic-zirconia": 190,
      "moissanite": 220,
      "vvs-lab-diamonds": 270,
      "vs-natural-diamonds": 320
    },
    "dental-gold": {
      "cubic-zirconia": 270,
      "moissanite": 320,
      "vvs-lab-diamonds": 370,
      "vs-natural-diamonds": 420
    },
    "9ct-yellow-gold": {
      "cubic-zirconia": 270,
      "moissanite": 320,
      "vvs-lab-diamonds": 370,
      "vs-natural-diamonds": 420
    },
    "9ct-white-gold": {
      "cubic-zirconia": 270,
      "moissanite": 320,
      "vvs-lab-diamonds": 370,
      "vs-natural-diamonds": 420
    },
    "14ct-yellow-gold": {
      "cubic-zirconia": 470,
      "moissanite": 520,
      "vvs-lab-diamonds": 570,
      "vs-natural-diamonds": 620
    },
    "14ct-white-gold": {
      "cubic-zirconia": 470,
      "moissanite": 520,
      "vvs-lab-diamonds": 570,
      "vs-natural-diamonds": 620
    }
  }
},
  IMPRESSION_KITS: [
  {
    id: "impression-kit-uk",
    kind: "kit",
    displayName: "Impression Kit (UK)",
    price: 20,
    region: "uk",
    image: null,
    blurb:
      "Take your impressions at home. Includes materials for 2 attempts and a prepaid UK return form.",
    includes: [...KIT_SHARED_INCLUDES, "Return postage form (UK only)"],
    returnNote: null,
  },
  {
    id: "impression-kit-international",
    kind: "kit",
    region: "international",
    displayName: "Impression Kit (International)",
    price: 10,
    image: null,
    blurb:
      "Take your impressions at home. Includes materials for 2 attempts. International clients find their own way to return the kit to us, using the return address found on the postage.",
    includes: [...KIT_SHARED_INCLUDES],
    returnNote:
      "Return postage is not prepaid. International clients find their own way to return the impression kit to us, using the return address found on the postage.",
  },
],
  ACCESSORIES: [
  {
    id: "gift-card",
    kind: "giftcard",
    displayName: "Krown Frontz Gift Card",
    price: 50,
    amounts: [50, 100, 150, 200, 250, 300, 350, 400],
    image: "assets/products/gift-card.jpg",
    imageAlt: "Krown Frontz gift card",
    blurb:
      "Hard to gift a specific style? A Krown Frontz gift card lets them choose their own custom grillz and accessories. After payment we’ll email you a code to pass on — they can use it toward a postal order, or as a deposit on an in-person appointment. Any remaining balance is settled when they come in.",
  },
  {
    id: "polish-cloth",
    kind: "accessory",
    displayName: "Jewellery polishing cloth",
    price: 3,
    image: null,
    imageAlt: "Jewellery polishing cloth",
    blurb:
      "Soft jewellery cloth for keeping your grillz bright between wears. Wipe gently after use to clear fingerprints and surface dullness — keep one with your set so a quick polish is always to hand. Best paired with a grillz case.",
  },
  {
    id: "grillz-case",
    kind: "accessory",
    displayName: "Grillz case",
    price: 5,
    image: null,
    imageAlt: "Protective grillz case",
    blurb:
      "A compact protective case so you never lose your set. Shields your grillz from scratches and knocks at home or on the go — drop them in when you’re not wearing them, and keep your polishing cloth alongside.",
  },
  {
    id: "repolish-service",
    kind: "service",
    displayName: "Grillz repolishing",
    price: 15,
    image: null,
    imageAlt: "Grillz repolishing service",
    blurb:
      "Send your set back for a professional polish. Post them to us (we email the studio return address after payment) or drop off in Manchester and pick them up when ready.",
  },
],
  PRODUCT_ID_ALIASES: {
  "basic-1": "canine",
  "basic-1-gold": "canine",
  "basic-2": "lateral",
  "basic-2-silver": "lateral",
  "basic-4": "plain-4",
  "basic-4-gold": "plain-4",
  "bar-4": "plain-4",
  "bar-6": "plain-6",
  "classic-6-gold": "plain-6",
  "bar-8": "plain-8",
  "bar-8-gold": "plain-8",
  "bar-12": "top-6-bottom-6",
  "full-gold": "top-8-bottom-8",
  "window-4": "open-face-4",
  "window-4-gold": "open-face-4",
  "window-6": "open-face-6",
  "open-silver": "open-face-6",
  "window-8": "window-set-8",
  "window-8-silver": "window-set-8",
  "window-12": "open-face-6-on-6",
  "window-16": "open-face-8-on-8",
  "top-4": "plain-4",
  "bottom-4": "plain-4",
  "top-6": "plain-6",
  "bottom-6": "plain-6",
  "top-8": "plain-8",
  "bottom-8": "plain-8",
  "heart-2": "heart-canine",
  "heart-2-gold": "heart-canine",
  "heart-4": "heart-canine-bar",
  "heart-4-gold": "heart-canine-bar",
  "vampire-2": "vampire-canines",
  "vampire-2-gold": "vampire-canines",
  "vampire-4": "vampire-canine-lateral-2",
  fangs: "vampire-canine-lateral-2",
  "diamond-4": "diamond-dust-4",
  "dust-4": "diamond-dust-4",
},
  PRODUCTS: [
  {
    id: "canine",
    displayName: "Canine",
    price: 90,
    compareAt: 115,
    image: null,
    imageAlt: "Canine grillz on dental model",
    finish: "gold",
    style: "basics",
    teeth: "1",
    toothRule: "single-canine",
    blurb: "Single canine cap. Custom-fitted.",
  },
  {
    id: "lateral",
    displayName: "Lateral",
    price: 95,
    compareAt: 115,
    image: null,
    imageAlt: "Lateral grillz on dental model",
    finish: "gold",
    style: "basics",
    teeth: "1",
    toothRule: "single-lateral",
    blurb: "Single lateral cap. Clean everyday look.",
  },
  {
    id: "central",
    displayName: "Central",
    price: 95,
    compareAt: 115,
    image: null,
    imageAlt: "Central incisor grillz on dental model",
    finish: "gold",
    style: "basics",
    teeth: "1",
    toothRule: "single-central",
    blurb: "Single central cap. Minimal statement.",
  },
  {
    id: "canine-canine",
    displayName: "2 x canines",
    price: 110,
    compareAt: 150,
    image: null,
    imageAlt: "Canine pair grillz on dental model",
    finish: "gold",
    style: "basics",
    teeth: "2",
    toothRule: "arch-canines",
    blurb: "Symmetric pair on upper or lower.",
  },
  {
    id: "lateral-lateral",
    displayName: "2 x Lateral",
    price: 110,
    compareAt: 140,
    image: null,
    imageAlt: "Lateral pair grillz on dental model",
    finish: "gold",
    style: "basics",
    teeth: "2",
    toothRule: "arch-laterals",
    blurb: "Both laterals on upper or lower. Clean double cap.",
  },
  {
    id: "canine-lateral-2x",
    displayName: "2 x Canine & Lateral",
    price: 175,
    compareAt: 225,
    image: null,
    imageAlt: "2 x canine and lateral grillz on dental model",
    finish: "gold",
    style: "basics",
    teeth: "4",
    toothRule: "both-side-canine-lateral",
    blurb: "Canine and lateral caps on two sides.",
  },
  {
    id: "lateral-canine",
    displayName: "Lateral & Canine",
    price: 110,
    compareAt: 140,
    image: null,
    imageAlt: "Lateral and canine grillz on dental model",
    finish: "gold",
    style: "basics",
    teeth: "2",
    toothRule: "lateral-canine-cross",
    blurb: "Lateral and canine caps — adjacent or opposite sides.",
  },
  {
    id: "canine-window",
    displayName: "Canine & Window",
    price: 110,
    compareAt: 135,
    pricingPremiumPerTooth: 5,
    image: null,
    imageAlt: "Canine and window grillz on dental model",
    finish: "gold",
    style: "basics",
    teeth: "2",
    toothRule: "canine-bar-pair",
    blurb: "Solid canine cap with window cut-out on the lateral.",
  },
  {
    id: "plain-4",
    displayName: "4 set",
    price: 350,
    compareAt: 410,
    image: null,
    imageAlt: "4 set grillz on dental model",
    finish: "gold",
    style: "basics",
    teeth: "4",
    toothRule: "contiguous-front",
    blurb: "Four contiguous front teeth. Choose upper or lower on the product page.",
  },
  {
    id: "canines-4",
    displayName: "4 x Canine",
    price: 220,
    compareAt: 280,
    image: null,
    imageAlt: "4 canine grillz on dental model",
    finish: "gold",
    style: "basics",
    teeth: "4",
    toothRule: "both-arch-canines",
    blurb: "All four canines. Upper and lower, left and right.",
  },
  {
    id: "laterals-4",
    displayName: "4 x Lateral",
    price: 220,
    compareAt: 280,
    image: null,
    imageAlt: "4 lateral grillz on dental model",
    finish: "gold",
    style: "basics",
    teeth: "4",
    toothRule: "both-arch-laterals",
    blurb: "All four laterals. Upper and lower, left and right.",
  },
  {
    id: "centrals-4",
    displayName: "4 x Central",
    price: 220,
    compareAt: 280,
    image: null,
    imageAlt: "4 central grillz on dental model",
    finish: "gold",
    style: "basics",
    teeth: "4",
    toothRule: "both-arch-centrals",
    blurb: "All four centrals. Upper and lower, left and right.",
  },
  {
    id: "plain-6",
    displayName: "6 set",
    price: 450,
    compareAt: 520,
    image: null,
    imageAlt: "6 set grillz on dental model",
    finish: "gold",
    style: "basics",
    teeth: "6",
    toothRule: "contiguous-front",
    blurb: "Six contiguous front teeth. Choose upper or lower on the product page.",
  },
  {
    id: "plain-8",
    displayName: "8 set",
    price: 580,
    compareAt: 650,
    image: null,
    imageAlt: "8 set grillz on dental model",
    finish: "gold",
    style: "basics",
    teeth: "8",
    toothRule: "contiguous-front",
    blurb: "Full front eight. Choose upper or lower on the product page.",
  },
  {
    id: "top-4-bottom-4",
    displayName: "4 on 4",
    price: 680,
    compareAt: 780,
    image: null,
    imageAlt: "Top 4 bottom 4 plain grillz on dental model",
    finish: "gold",
    style: "basics",
    teeth: "8",
    toothRule: "both-arch-contiguous",
    chartMode: "both",
    blurb: "Four contiguous teeth on top and bottom. Plain set.",
  },
  {
    id: "top-6-bottom-6",
    displayName: "6 on 6",
    price: 900,
    compareAt: 1050,
    image: null,
    imageAlt: "Top 6 bottom 6 plain grillz on dental model",
    finish: "gold",
    style: "basics",
    teeth: "12",
    toothRule: "both-arch-contiguous",
    chartMode: "both",
    blurb: "Six contiguous teeth on top and bottom. Plain full smile.",
  },
  {
    id: "top-8-bottom-8",
    displayName: "8 on 8",
    price: 1200,
    compareAt: 1350,
    image: null,
    imageAlt: "Top 8 bottom 8 plain grillz on dental model",
    finish: "gold",
    style: "basics",
    teeth: "16",
    toothRule: "both-arch-contiguous",
    chartMode: "both",
    blurb: "Eight contiguous teeth on top and bottom. Maximum plain set.",
  },
  {
    id: "window-canine-bar",
    displayName: "Window Canine & Inlay",
    price: 115,
    compareAt: 135,
    image: null,
    imageAlt: "Window canine and inlay grillz on dental model",
    finish: "gold",
    style: "bar",
    teeth: "2",
    toothRule: "canine-bar-pair",
    blurb: "Window canine with inlay on the lateral.",
  },
  {
    id: "canine-bar",
    displayName: "Canine & Inlay",
    price: 110,
    compareAt: 135,
    pricingPremiumPerTooth: 5,
    image: null,
    imageAlt: "Canine and inlay grillz on dental model",
    finish: "gold",
    style: "bar",
    teeth: "2",
    toothRule: "canine-bar-pair",
    blurb: "Solid canine cap linked to a lateral inlay.",
  },
  {
    id: "heart-canine-bar",
    displayName: "Heart Canine & Inlay",
    price: 295,
    compareAt: 335,
    pricingPremiumPerTooth: 20,
    image: null,
    imageAlt: "Heart canine and inlay grillz on dental model",
    finish: "gold",
    style: "bar",
    teeth: "2",
    toothRule: "canine-bar-pair",
    blurb: "Heart window canine with lateral inlay.",
  },
  {
    id: "canines-bar-2x",
    displayName: "2 x Canine & Inlay",
    price: 235,
    compareAt: 265,
    pricingSterlingBase: 225,
    pricingPremiumBase: 235,
    pricingPremiumPerTooth: 0,
    image: null,
    imageAlt: "Lower canine and inlay grillz on dental model",
    finish: "gold",
    style: "bar",
    teeth: "6",
    chartMode: "lower",
    toothRule: "contiguous-front",
    blurb: "Lower canines connected by an inlay across the front four.",
  },
  {
    id: "window-canine",
    displayName: "Window Canine",
    price: 105,
    compareAt: 125,
    image: null,
    imageAlt: "Window canine grillz on dental model",
    finish: "gold",
    style: "window",
    teeth: "1",
    toothRule: "single-canine",
    blurb: "Cut-out window on the canine.",
  },
  {
    id: "window-lateral",
    displayName: "Window Lateral",
    price: 105,
    compareAt: 125,
    image: null,
    imageAlt: "Window lateral grillz on dental model",
    finish: "gold",
    style: "window",
    teeth: "1",
    toothRule: "single-lateral",
    blurb: "Cut-out window on the lateral.",
  },
  {
    id: "window-canine-lateral-2",
    displayName: "Window Canine & Window Lateral",
    price: 245,
    compareAt: 285,
    image: null,
    imageAlt: "Window canine and window lateral grillz on dental model",
    finish: "gold",
    style: "window",
    teeth: "2",
    toothRule: "canine-lateral-pair",
    blurb: "Window cuts on canine and lateral pair.",
  },
  {
    id: "open-face-4",
    displayName: "4 set open face",
    price: 240,
    compareAt: 280,
    image: null,
    imageAlt: "4 set open face grillz on dental model",
    finish: "gold",
    style: "window",
    teeth: "4",
    toothRule: "contiguous-front",
    blurb: "Cut-out windows on the front four.",
  },
  {
    id: "open-face-6",
    displayName: "6 set open face",
    price: 280,
    compareAt: 320,
    image: null,
    imageAlt: "6 set open face grillz on dental model",
    finish: "silver",
    style: "window",
    teeth: "6",
    toothRule: "contiguous-front",
    blurb: "Open face frame. Natural tooth shows through.",
  },
  {
    id: "window-set-8",
    displayName: "8 set open face",
    price: 580,
    compareAt: 640,
    pricingSterlingBase: 305,
    image: null,
    imageAlt: "8 set open face grillz on dental model",
    finish: "silver",
    style: "window",
    teeth: "8",
    toothRule: "contiguous-front",
    blurb: "Full window set. Thin cut-out frames.",
  },
  {
    id: "open-face-6-on-6",
    displayName: "6 on 6 open face",
    price: 560,
    compareAt: 640,
    pricingSterlingBase: 460,
    image: null,
    imageAlt: "6 on 6 open face grillz on dental model",
    finish: "silver",
    style: "window",
    teeth: "12",
    toothRule: "both-arch-contiguous",
    chartMode: "both",
    blurb: "Open face frames on upper and lower. Six contiguous teeth.",
  },
  {
    id: "open-face-8-on-8",
    displayName: "8 on 8 open face",
    price: 1160,
    compareAt: 1280,
    pricingPremiumPerTooth: 5,
    image: null,
    imageAlt: "8 on 8 open face grillz on dental model",
    finish: "silver",
    style: "window",
    teeth: "16",
    toothRule: "both-arch-contiguous",
    chartMode: "both",
    blurb: "Full open face set. Eight contiguous teeth on top and bottom.",
  },
  {
    id: "heart-canine",
    displayName: "Heart Canine",
    price: 165,
    compareAt: 195,
    image: null,
    imageAlt: "Heart window canine grillz on dental model",
    finish: "gold",
    style: "heart",
    teeth: "1",
    toothRule: "single-canine",
    blurb: "Heart-shaped window on the canine.",
  },
  {
    id: "heart-lateral",
    displayName: "Heart Lateral",
    price: 165,
    compareAt: 195,
    image: null,
    imageAlt: "Heart window lateral grillz on dental model",
    finish: "gold",
    style: "heart",
    teeth: "1",
    toothRule: "single-lateral",
    blurb: "Heart-shaped window on the lateral.",
  },
  {
    id: "star-canine",
    displayName: "Star Canine",
    price: 165,
    compareAt: 195,
    image: null,
    imageAlt: "Star cut-out canine grillz on dental model",
    finish: "gold",
    style: "star",
    teeth: "1",
    toothRule: "single-canine",
    blurb: "Star cut-out on the canine.",
  },
  {
    id: "star-lateral",
    displayName: "Star Lateral",
    price: 165,
    compareAt: 195,
    image: null,
    imageAlt: "Star cut-out lateral grillz on dental model",
    finish: "gold",
    style: "star",
    teeth: "1",
    toothRule: "single-lateral",
    blurb: "Star cut-out on the lateral.",
  },
  {
    id: "star-abstract-2",
    displayName: "Abstract Star",
    price: 245,
    compareAt: 285,
    pricingSterlingBase: 115,
    image: null,
    imageAlt: "Abstract star grillz spanning two teeth on dental model",
    finish: "gold",
    style: "star",
    teeth: "2",
    toothRule: "contiguous-front",
    chartMode: "upper",
    blurb: "Abstract star design spanning two contiguous upper front teeth.",
  },
  {
    id: "vampire-canines",
    displayName: "Vampire Canines",
    price: 175,
    compareAt: 210,
    pricingSterlingBase: 115,
    image: null,
    imageAlt: "Vampire canine grillz on dental model",
    finish: "gold",
    style: "vampire",
    teeth: "2",
    toothRule: "arch-canines",
    blurb: "Pointed vampire canines. Sharp pair.",
  },
  {
    id: "vampire-canine-lateral-2",
    displayName: "Vampire Canine & Lateral",
    price: 245,
    compareAt: 285,
    pricingPremiumPerTooth: 5,
    image: null,
    imageAlt: "Vampire canine and lateral grillz on dental model",
    finish: "gold",
    style: "vampire",
    teeth: "2",
    toothRule: "canine-lateral-pair",
    blurb: "Extended canines with lateral caps.",
  },
  {
    id: "dust-canine",
    displayName: "Diamond-dust Canine",
    price: 120,
    compareAt: 145,
    image: null,
    imageAlt: "Diamond-dust canine grillz on dental model",
    finish: "gold",
    style: "diamond",
    teeth: "1",
    toothRule: "single-canine",
    blurb: "Micro-cut dust finish on a single canine.",
  },
  {
    id: "dust-lateral",
    displayName: "Diamond-dust Lateral",
    price: 125,
    compareAt: 145,
    image: null,
    imageAlt: "Diamond-dust lateral grillz on dental model",
    finish: "gold",
    style: "diamond",
    teeth: "1",
    toothRule: "single-lateral",
    blurb: "Micro-cut dust finish on a single lateral.",
  },
  {
    id: "dust-central",
    displayName: "Diamond-dust Central",
    price: 125,
    compareAt: 145,
    image: null,
    imageAlt: "Diamond-dust central grillz on dental model",
    finish: "gold",
    style: "diamond",
    teeth: "1",
    toothRule: "single-central",
    blurb: "Micro-cut dust finish on a single central.",
  },
  {
    id: "dust-canine-pair",
    displayName: "2 x Diamond-dust Canine",
    price: 150,
    compareAt: 190,
    image: null,
    imageAlt: "Diamond-dust canine pair grillz on dental model",
    finish: "gold",
    style: "diamond",
    teeth: "2",
    toothRule: "arch-canines",
    blurb: "Dust finish on both canines on upper or lower.",
  },
  {
    id: "dust-lateral-pair",
    displayName: "2 x Diamond-dust Lateral",
    price: 150,
    compareAt: 180,
    image: null,
    imageAlt: "Diamond-dust lateral pair grillz on dental model",
    finish: "gold",
    style: "diamond",
    teeth: "2",
    toothRule: "arch-laterals",
    blurb: "Dust finish on both laterals on upper or lower.",
  },
  {
    id: "dust-central-pair",
    displayName: "2 x Diamond-dust Central",
    price: 150,
    compareAt: 180,
    image: null,
    imageAlt: "Diamond-dust central pair grillz on dental model",
    finish: "gold",
    style: "diamond",
    teeth: "2",
    toothRule: "arch-centrals",
    blurb: "Dust finish on both centrals on upper or lower.",
  },
  {
    id: "dust-canines-4",
    displayName: "4 x Diamond-dust Canine",
    price: 280,
    compareAt: 340,
    image: null,
    imageAlt: "Diamond-dust 4 canine grillz on dental model",
    finish: "gold",
    style: "diamond",
    teeth: "4",
    toothRule: "both-arch-canines",
    blurb: "Dust finish on all four canines.",
  },
  {
    id: "dust-laterals-4",
    displayName: "4 x Diamond-dust Lateral",
    price: 280,
    compareAt: 340,
    image: null,
    imageAlt: "Diamond-dust 4 lateral grillz on dental model",
    finish: "gold",
    style: "diamond",
    teeth: "4",
    toothRule: "both-arch-laterals",
    blurb: "Dust finish on all four laterals.",
  },
  {
    id: "dust-centrals-4",
    displayName: "4 x Diamond-dust Central",
    price: 280,
    compareAt: 340,
    image: null,
    imageAlt: "Diamond-dust 4 central grillz on dental model",
    finish: "gold",
    style: "diamond",
    teeth: "4",
    toothRule: "both-arch-centrals",
    blurb: "Dust finish on all four centrals.",
  },
  {
    id: "diamond-dust-4",
    displayName: "4 x Diamond-dust set",
    price: 320,
    compareAt: 380,
    image: null,
    imageAlt: "Diamond-dust 4-tooth grillz on dental model",
    finish: "gold",
    style: "diamond",
    teeth: "4",
    toothRule: "contiguous-front",
    blurb: "Micro-cut dust finish. Glitter without stones.",
  },
  {
    id: "diamond-canine",
    displayName: "Diamond Canine",
    price: 360,
    compareAt: 420,
    image: null,
    imageAlt: "Diamond canine grillz on dental model",
    finish: "iced",
    style: "diamond",
    teeth: "1",
    toothRule: "single-canine",
    blurb: "Hand-set stones on a single canine cap.",
  },
  {
    id: "diamond-lateral",
    displayName: "Diamond Lateral",
    price: 290,
    compareAt: 340,
    image: null,
    imageAlt: "Diamond lateral grillz on dental model",
    finish: "iced",
    style: "diamond",
    teeth: "1",
    toothRule: "single-lateral",
    blurb: "Hand-set stones on a single lateral cap.",
  },
  {
    id: "diamond-heart-canine",
    displayName: "Diamond Heart Canine",
    price: 320,
    compareAt: 375,
    image: null,
    imageAlt: "Diamond heart canine grillz on dental model",
    finish: "iced",
    style: "diamond",
    teeth: "1",
    toothRule: "single-canine",
    blurb: "Heart window canine with hand-set stones.",
  },
  {
    id: "diamond-window-canine",
    displayName: "Diamond Window Canine",
    price: 260,
    compareAt: 305,
    image: null,
    imageAlt: "Diamond window canine grillz on dental model",
    finish: "iced",
    style: "diamond",
    teeth: "1",
    toothRule: "single-canine",
    blurb: "Window canine with hand-set stones.",
  },
  {
    id: "diamond-canine-canine",
    displayName: "2 x Diamond Canine",
    price: 630,
    compareAt: 720,
    image: null,
    imageAlt: "Diamond canine pair grillz on dental model",
    finish: "iced",
    style: "diamond",
    teeth: "2",
    toothRule: "arch-canines",
    blurb: "Hand-set stones on both canines on upper or lower.",
  },
  {
    id: "diamond-lateral-lateral",
    displayName: "2 x Diamond Lateral",
    price: 490,
    compareAt: 560,
    image: null,
    imageAlt: "Diamond lateral pair grillz on dental model",
    finish: "iced",
    style: "diamond",
    teeth: "2",
    toothRule: "arch-laterals",
    blurb: "Hand-set stones on both laterals on upper or lower.",
  },
  {
    id: "diamond-lateral-canine",
    displayName: "Diamond Lateral & Canine",
    price: 560,
    compareAt: 640,
    image: null,
    imageAlt: "Diamond lateral and canine grillz on dental model",
    finish: "iced",
    style: "diamond",
    teeth: "2",
    toothRule: "canine-lateral-pair",
    blurb: "Hand-set stones on canine and lateral pair.",
  },
  {
    id: "diamond-window-canine-inlay",
    displayName: "Diamond Window Canine & Inlay",
    price: 275,
    compareAt: 320,
    image: null,
    imageAlt: "Diamond window canine and inlay grillz on dental model",
    finish: "iced",
    style: "diamond",
    teeth: "2",
    toothRule: "canine-bar-pair",
    blurb: "Window canine with diamond-set lateral inlay.",
  },
  {
    id: "diamond-window-lateral-canine",
    displayName: "Diamond Window Lateral & Canine",
    price: 350,
    compareAt: 405,
    image: null,
    imageAlt: "Diamond window lateral and canine grillz on dental model",
    finish: "iced",
    style: "diamond",
    teeth: "2",
    toothRule: "canine-lateral-pair",
    blurb: "Window cuts with hand-set stones on canine and lateral.",
  },
  {
    id: "window-canine-diamond-inlay",
    displayName: "Window Canine & Diamond Inlay",
    price: 220,
    compareAt: 260,
    image: null,
    imageAlt: "Window canine and diamond inlay grillz on dental model",
    finish: "iced",
    style: "diamond",
    teeth: "2",
    toothRule: "canine-bar-pair",
    blurb: "Window canine with diamond-set lateral inlay.",
  },

],
  BASE_TIERS: {
  sterling: { 1: 55, 2: 100, 4: 190, 6: 275, 8: 330, 16: 550 },
  premium: { 1: 60, 2: 110, 4: 200, 6: 300, 8: 385, 16: 590 },
},
  PRECIOUS_SINGLE_9CT: 155,
  PRECIOUS_SINGLE_14CT: 200,
  DUAL_ARCH_4ON4_IDS: new Set(["top-4-bottom-4"]),
  DUAL_ARCH_6ON6_IDS: new Set(["top-6-bottom-6", "open-face-6-on-6"]),
  DUAL_ARCH_8ON8_IDS: new Set(["top-8-bottom-8", "open-face-8-on-8"]),
};
